# Window (title, geometry)
window:
    title: ASTRA Tutorial Session - Plex Reduced
    x: 400
    y: 600

# 3D widget
widget:
    manipulator: TRACKBALL_MANIPULATOR
    background: [200,160,30]
    axes: False
    transformer: False

# Plugins
plugins:
    - type: RigidBodyStateVisualization
      name: rbs
      modelPath: bridget.stl
      enabled: False
      frame:
          base: world_osg
          position: [1, 1, 1]
          rotation: [1, 0, 0, 0]
          # rotation quaternion in order [w, x, y, z]
    - type: ModelVisualization
      enabled: False
      modelPath: stim300.stl

    - type: GridVisualization
